### ISSUE TITLE
mBlock 5 extension

### ISSUE THREAD

**Issue by zYl0riC** [emakefun/MotorDriverBoard#1]
hi emakefun,

I like your great MotorDriverBoard. Currently I got some trouble to use the s2e-extension from old mBlock version in the current version 5. The new version got an own extension manager and a new ext-structure (with .json and index.js file)
Is it possible to add a mBlock5 extension in the scratch/mBlock folder.

Would be great.
Best regards
zYloriC

**Comment by josestevez-bit** [comment]
Hola: Tengo un shield Emakefun MotorDriveBoard V5.0 y no se como puedo acceder para subir sketchs o modifiucar los ejemplos; no se que librería utilizar. Ayuda por favor.

**Comment by emakefun** [comment]
Dears 

 

Commit : https://github.com/emakefun/MotorDriverBoard/commit/aa01c2909c57a15c4bd8f2b24d0c2ecaf88f4dc4

 

 

ken

发件人: josestevez-bit <notifications@github.com> 
发送时间: 2020年4月21日 22:26
收件人: emakefun/MotorDriverBoard <MotorDriverBoard@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [emakefun/MotorDriverBoard] mBlock 5 extension (#1)

 

Hola: Tengo un shield Emakefun MotorDriveBoard V5.0 y no se como puedo acceder para subir sketchs o modifiucar los ejemplos; no se que librería utilizar. Ayuda por favor.

**Comment by MQint** [comment]
i can't add this extension in mblock 5 ( File error , Install Filed )

**Comment by emakefun** [comment]
add it
