### ISSUE TITLE
MotorDriverBoard自带范例pwm_test未正常输出波形

### ISSUE THREAD

**Issue by GeekThomas** [emakefun/MotorDriverBoard#4]
Arduino版本号：1.8.15
使用自带范例pwm_test未正常输出波形，使用其他第三方库Adafruit_PWMServoDriver测试输出正常。

**Comment by nulllaborg** [comment]
fix on 1d8a1cbba02f31783b632304873a959649eb077d

**Comment by emakefun** [comment]
fix on 1d8a1cbba02f31783b632304873a959649eb077d
